name: Render video
on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Which text should it say?"
        required: false
        default: "Welcome to Remotion"
      titleColor:
        description: "Which color should it be in?"
        required: false
        default: "black"
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      # - run: npm i
      # - run: echo $WORKFLOW_INPUT > input-props.json
      #   env:
      #     WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: pnpm build
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4
